-- MySQL Script generated by MySQL Workbench
-- Sun Nov  6 20:15:11 2016
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema gymManagementProject
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema gymManagementProject
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `gymManagementProject` DEFAULT CHARACTER SET latin1 ;
USE `gymManagementProject` ;

-- -----------------------------------------------------
-- Table `gymManagementProject`.`attendance`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gymManagementProject`.`attendance` (
  `aStartTime` VARCHAR(100) NULL DEFAULT NULL,
  `aEndTime` VARCHAR(100) NULL DEFAULT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `gymManagementProject`.`worker`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gymManagementProject`.`worker` (
  `wId` MEDIUMINT(9) NOT NULL,
  `wFirstName` VARCHAR(100) NOT NULL,
  `wLastName` VARCHAR(100) NOT NULL,
  `wJoinTime` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `wEmail` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`wId`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `gymManagementProject`.`personalTrainer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gymManagementProject`.`personalTrainer` (
  `wId` MEDIUMINT(9) NOT NULL,
  `ptFirstName` VARCHAR(100) NULL DEFAULT NULL,
  `ptLastName` VARCHAR(100) NULL DEFAULT NULL,
  `ptEmail` VARCHAR(100) NULL DEFAULT NULL,
  `availableTime` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`wId`),
  CONSTRAINT `personaltrainer_ibfk_1`
    FOREIGN KEY (`wId`)
    REFERENCES `gymManagementProject`.`worker` (`wId`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `gymManagementProject`.`availableTimeSlot`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gymManagementProject`.`availableTimeSlot` (
  `aStartTime` VARCHAR(100) NULL DEFAULT NULL,
  `aEndTime` VARCHAR(100) NULL DEFAULT NULL,
  `wid` MEDIUMINT(9) NOT NULL,
  `availability` TINYINT(1) NOT NULL,
  PRIMARY KEY (`wid`),
  CONSTRAINT `availabletimeslot_ibfk_1`
    FOREIGN KEY (`wid`)
    REFERENCES `gymManagementProject`.`personalTrainer` (`wId`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `gymManagementProject`.`customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gymManagementProject`.`customer` (
  `cId` MEDIUMINT(9) NOT NULL,
  `cFirstName` VARCHAR(100) NOT NULL,
  `cLastName` VARCHAR(100) NOT NULL,
  `cJoinTime` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `cEmail` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`cId`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `gymManagementProject`.`booked`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gymManagementProject`.`booked` (
  `cId` MEDIUMINT(9) NOT NULL,
  `wId` MEDIUMINT(9) NOT NULL,
  PRIMARY KEY (`cId`),
  INDEX `wId` (`wId` ASC),
  CONSTRAINT `booked_ibfk_1`
    FOREIGN KEY (`cId`)
    REFERENCES `gymManagementProject`.`customer` (`cId`),
  CONSTRAINT `booked_ibfk_2`
    FOREIGN KEY (`wId`)
    REFERENCES `gymManagementProject`.`worker` (`wId`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `gymManagementProject`.`cleaner`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gymManagementProject`.`cleaner` (
  `wId` MEDIUMINT(9) NOT NULL,
  `rFirstName` VARCHAR(100) NULL DEFAULT NULL,
  `rLastName` VARCHAR(100) NULL DEFAULT NULL,
  `rEmail` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`wId`),
  CONSTRAINT `cleaner_ibfk_1`
    FOREIGN KEY (`wId`)
    REFERENCES `gymManagementProject`.`worker` (`wId`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `gymManagementProject`.`manager`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gymManagementProject`.`manager` (
  `wId` MEDIUMINT(9) NOT NULL AUTO_INCREMENT,
  `wFirstName` VARCHAR(100) NOT NULL,
  `wLastName` VARCHAR(100) NOT NULL,
  `wJoinTime` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `wEmail` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`wId`),
  CONSTRAINT `manager_ibfk_1`
    FOREIGN KEY (`wId`)
    REFERENCES `gymManagementProject`.`worker` (`wId`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `gymManagementProject`.`membershipConsultant`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gymManagementProject`.`membershipConsultant` (
  `wId` MEDIUMINT(9) NOT NULL,
  `mcFirstName` VARCHAR(100) NULL DEFAULT NULL,
  `mcLastName` VARCHAR(100) NULL DEFAULT NULL,
  `mcEmail` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`wId`),
  CONSTRAINT `membershipconsultant_ibfk_1`
    FOREIGN KEY (`wId`)
    REFERENCES `gymManagementProject`.`worker` (`wId`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `gymManagementProject`.`permCustomer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gymManagementProject`.`permCustomer` (
  `cId` MEDIUMINT(9) NOT NULL,
  `pcFirstName` VARCHAR(100) NOT NULL,
  `pcLastName` VARCHAR(100) NOT NULL,
  `pcEmail` VARCHAR(100) NOT NULL,
  `type` VARCHAR(100) NOT NULL,
  `expireDate` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`cId`),
  CONSTRAINT `permcustomer_ibfk_1`
    FOREIGN KEY (`cId`)
    REFERENCES `gymManagementProject`.`customer` (`cId`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `gymManagementProject`.`receptionist`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gymManagementProject`.`receptionist` (
  `wId` MEDIUMINT(9) NOT NULL,
  `rFirstName` VARCHAR(100) NULL DEFAULT NULL,
  `rLastName` VARCHAR(100) NULL DEFAULT NULL,
  `rEmail` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`wId`),
  CONSTRAINT `receptionist_ibfk_1`
    FOREIGN KEY (`wId`)
    REFERENCES `gymManagementProject`.`worker` (`wId`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `gymManagementProject`.`tempCustomer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gymManagementProject`.`tempCustomer` (
  `cId` MEDIUMINT(9) NOT NULL,
  `tcFirstName` VARCHAR(100) NOT NULL,
  `tcLastName` VARCHAR(100) NOT NULL,
  `tcEmail` VARCHAR(100) NOT NULL,
  `timesLeft` INT(11) NOT NULL,
  `timesUsed` INT(11) NOT NULL,
  PRIMARY KEY (`cId`),
  CONSTRAINT `tempcustomer_ibfk_1`
    FOREIGN KEY (`cId`)
    REFERENCES `gymManagementProject`.`customer` (`cId`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
